# Generated by Django 5.1.4 on 2025-01-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_rename_title_property_bhk_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
