# Generated by Django 5.1.4 on 2025-01-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='area',
        ),
    ]
