# Generated by Django 5.1.4 on 2025-01-15 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_remove_property_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='contact_details',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='BHK_type',
            new_name='title',
        ),
    ]
