# Generated by Django 5.1.4 on 2025-01-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
